name: Go tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  go_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.5.0
      id: setup-go-faster
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
      if: ${{ runner.os == 'Linux' }}
      
    - name: Test
      run: go test ./...
